spring:
  application:
  name: diarioGlicemia

  datasource:
    url: ${DATABASE_URL}
    #    docker run --name database -p 2222:5432 -e POSTGRES_PASSWORD=postgres -d postgres
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

diarioGlicemia:
  security:
    secret: "palavra-secreta"