name: Deploy na AWS

on:
  push:
    branches: [ main ] # O deploy acontece sempre que você der push na main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar comandos remotos via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/diarioGlicemia
            git pull origin main
            docker stop meu-container-glicemia || true
            docker rm meu-container-glicemia || true
            docker build -t app-glicemia .
            docker run -d --network host --name meu-container-glicemia \
              -e PGHOST=localhost \
              -e PGDATABASE=diario_glicemia \
              -e PGUSER=postgres \
              -e PGPASSWORD=${{ secrets.PG_PASSWORD }} \
              app-glicemia